name = "cloudflare-proxy-typescript"
type = "webpack"
account_id = ""
workers_dev = true
webpack_config = "webpack.config.js"
compatibility_date = "2022-02-23"

[env.production]
workers_dev = true
route = "https://auston.dev/*"
zone_id = "1bc507a81a4fd53bb0327976ab1bc09f"
